apiVersion: apps/v1
kind: Deployment
metadata:
  name: llmops-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: llmops-app
  template:
    metadata:
      labels:
        app: llmops-app
    spec:
      containers:
      - name: llmops-app
<<<<<<< HEAD
        image:ayushbh01/studybuddy:latest
=======
        image: ayushbh01/studybuddy:v25
>>>>>>> e55da16d0938cddd1d7c3561239ea6c31a05cb8f
        ports:
        - containerPort: 8501
        env:
        - name: GROQ_API_KEY
          valueFrom:
            secretKeyRef:
              name: groq-api-secret
              key: GROQ_API_KEY
